# Setup

In [6]:
import os
import sys
from pathlib import Path

import pandas as pd
import plotly.express as px

sys.path.insert(0, str(Path("").resolve().parents[1]))
from utils.db_manager import MimicDBManager

In [3]:
width = 1200
height = 600
img_path = "./images"
Path(img_path).mkdir(parents=True, exist_ok=True)
plot_fig = False
pd.set_option("display.max_rows", 100)

In [5]:
db_manager = MimicDBManager(port=5432)
db_manager.retrieve_table_names()

[2024-10-26 12:57:39,611 - db_manager.py:51 - generate_connection() - INFO Creating connection to PostgreSQL

['mimiciv_hosp.admissions',
 'mimiciv_hosp.d_hcpcs',
 'mimiciv_hosp.diagnoses_icd',
 'mimiciv_hosp.d_icd_diagnoses',
 'mimiciv_hosp.d_icd_procedures',
 'mimiciv_hosp.d_labitems',
 'mimiciv_hosp.drgcodes',
 'mimiciv_hosp.emar_detail',
 'mimiciv_hosp.emar',
 'mimiciv_hosp.hcpcsevents',
 'mimiciv_hosp.labevents',
 'mimiciv_hosp.microbiologyevents',
 'mimiciv_hosp.omr',
 'mimiciv_hosp.patients',
 'mimiciv_hosp.pharmacy',
 'mimiciv_hosp.poe_detail',
 'mimiciv_hosp.poe',
 'mimiciv_hosp.prescriptions',
 'mimiciv_hosp.procedures_icd',
 'mimiciv_hosp.provider',
 'mimiciv_hosp.services',
 'mimiciv_hosp.transfers',
 'mimiciv_icu.caregiver',
 'mimiciv_icu.chartevents',
 'mimiciv_icu.datetimeevents',
 'mimiciv_icu.d_items',
 'mimiciv_icu.icustays',
 'mimiciv_icu.ingredientevents',
 'mimiciv_icu.inputevents',
 'mimiciv_icu.outputevents',
 'mimiciv_icu.procedureevents',
 'mimiciv_derived.urine_output',
 'mimiciv_derived.kdigo_creatinine',
 'mimiciv_derived.weight_durations',
 'mimiciv_derived.kdigo_uo',
 'mimiciv_derived.crrt',
 'mimiciv_derived.kdigo_stages',
 'mimiciv_derived.icustay_detail']

In [4]:
tables = (
    pd.DataFrame.from_dict(
        {table: db_manager.retrieve_column_types(table) for table in db_manager.retrieve_table_names()}, orient="index"
    )
    .fillna("-")
    .sort_index()
    .reset_index(names="full_table_name")
)
tables[["parent_table", "table_name"]] = tables.full_table_name.str.split(".", expand=True)

In [7]:
[table for table in tables.table_name.to_list() if "input" in table]

['inputevents']

In [5]:
table = "inputevents"
table_of_interest = tables[tables.table_name == table]
table_of_interest.loc[:, ~(table_of_interest == "-").all()].columns

Index(['full_table_name', 'subject_id', 'hadm_id', 'itemid', 'storetime',
       'starttime', 'caregiver_id', 'originalrate', 'stay_id', 'endtime',
       'amount', 'orderid', 'linkorderid', 'patientweight', 'totalamount',
       'isopenbag', 'continueinnextdept', 'originalamount', 'rate',
       'amountuom', 'ordercategorydescription', 'rateuom', 'totalamountuom',
       'statusdescription', 'ordercategoryname', 'secondaryordercategoryname',
       'ordercomponenttypedescription', 'parent_table', 'table_name'],
      dtype='object')

In [6]:
[table for table in tables.table_name.to_list() if "vent" in table]

['ventilation',
 'ventilator_setting',
 'hcpcsevents',
 'labevents',
 'microbiologyevents',
 'chartevents',
 'datetimeevents',
 'ingredientevents',
 'inputevents',
 'outputevents',
 'procedureevents']

In [11]:
table = "ventilation"
table_of_interest = tables[tables.table_name == table]
table_of_interest.loc[:, ~(table_of_interest == "-").all()].columns

Index(['full_table_name', 'starttime', 'stay_id', 'endtime',
       'ventilation_status', 'parent_table', 'table_name'],
      dtype='object')

In [10]:
[table for table in tables.table_name.to_list() if "kdigo" in table]

['kdigo_creatinine', 'kdigo_stages', 'kdigo_uo']

In [13]:
table = "kdigo_stages"
table_of_interest = tables[tables.table_name == table]
table_of_interest.loc[:, ~(table_of_interest == "-").all()]

,full_table_name,subject_id,hadm_id,charttime,stay_id,uo_rt_6hr,uo_rt_12hr,uo_rt_24hr,creat,creat_low_past_48hr,creat_low_past_7day,aki_stage_creat,aki_stage_uo,aki_stage_crrt,aki_stage,aki_stage_smoothed,parent_table,table_name
36,mimiciv_derived.kdigo_stages,integer,integer,timestamp without time zone,integer,numeric,numeric,numeric,double precision,double precision,double precision,integer,integer,integer,integer,integer,mimiciv_derived,kdigo_stages

In [14]:
[table for table in tables.table_name.to_list() if "vaso" in table]

['vasoactive_agent', 'vasopressin']

In [16]:
table = "vasoactive_agent"
table_of_interest = tables[tables.table_name == table]
table_of_interest.loc[:, ~(table_of_interest == "-").all()].columns

Index(['full_table_name', 'starttime', 'stay_id', 'endtime', 'dopamine',
       'epinephrine', 'norepinephrine', 'phenylephrine', 'vasopressin',
       'dobutamine', 'milrinone', 'parent_table', 'table_name'],
      dtype='object')

In [17]:
table = "vasopressin"
table_of_interest = tables[tables.table_name == table]
table_of_interest.loc[:, ~(table_of_interest == "-").all()].columns

Index(['full_table_name', 'starttime', 'stay_id', 'endtime', 'linkorderid',
       'vaso_rate', 'vaso_amount', 'parent_table', 'table_name'],
      dtype='object')

# Check csv generated

The csv files contained the parameters required for the training. Let's check their values

In [16]:
csv_path = Path("../../data/labs-kdigo_stages_measured.csv")
df_kdigo = pd.read_csv(csv_path, sep=";")
df_kdigo.head()

,subject_id,hadm_id,stay_id,charttime,aniongap_min,aniongap_max,albumin_min,albumin_max,bands_min,bands_max,...,inr_min,inr_max,pt_min,pt_max,sodium_min,sodium_max,bun_min,bun_max,wbc_min,wbc_max
0,10000032,29079034,39553978,2180-07-23 21:45:00,14.0,14.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,132.0,132.0,33.0,33.0,NaN,NaN
1,10000032,29079034,39553978,2180-07-24 06:35:00,9.0,9.0,3.8,3.8,NaN,NaN,...,1.8,1.8,19.5,19.5,130.0,130.0,28.0,28.0,4.1,4.1
2,10000032,29079034,39553978,2180-07-25 04:45:00,11.0,11.0,NaN,NaN,NaN,NaN,...,2.0,2.0,21.6,21.6,130.0,130.0,35.0,35.0,4.8,4.8
3,10000980,26913865,39765666,2189-06-27 20:03:00,NaN,NaN,NaN,NaN,NaN,NaN,...,1.3,1.3,14.5,14.5,NaN,NaN,NaN,NaN,NaN,NaN
4,10000980,26913865,39765666,2189-06-28 06:15:00,17.0,17.0,NaN,NaN,NaN,NaN,...,1.3,1.3,14.3,14.3,139.0,139.0,38.0,38.0,5.4,5.4

In [18]:
vars_of_interest = [
    "aniongap_min",
    "aniongap_max",
    "bicarbonate_min",
    "bicarbonate_max",
    "creatinine_min",
    "creatinine_max",
    "chloride_min",
    "chloride_max",
    "glucose_min",
    "glucose_max",
    "hematocrit_min",
    "hematocrit_max",
    "hemoglobin_min",
    "hemoglobin_max",
    "potassium_min",
    "potassium_max",
    "sodium_min",
    "sodium_max",
    "bun_min",
    "bun_max",
]

In [19]:
nan_percentage = df_kdigo.isna().mean() * 100

In [20]:
nan_percentage[vars_of_interest]

aniongap_min       46.050895
aniongap_max       46.050895
bicarbonate_min    45.891892
bicarbonate_max    45.891892
creatinine_min     45.445698
creatinine_max     45.445698
chloride_min       40.768004
chloride_max       40.768004
glucose_min        36.587705
glucose_max        36.587705
hematocrit_min     40.387267
hematocrit_max     40.387267
hemoglobin_min     44.703615
hemoglobin_max     44.703615
potassium_min      33.146188
potassium_max      33.146188
sodium_min         38.779786
sodium_max         38.779786
bun_min            45.602867
bun_max            45.602867
dtype: float64

In [21]:
csv_path = Path("../../data/vitals-kdigo_stages_measured.csv")
df_vitals = pd.read_csv(csv_path, sep=";")
df_vitals.head()

,subject_id,hadm_id,stay_id,charttime,heartrate_min,heartrate_max,heartrate_mean,sysbp_min,sysbp_max,sysbp_mean,...,resprate_mean,tempc_min,tempc_max,tempc_mean,spo2_min,spo2_max,spo2_mean,glucose_min,glucose_max,glucose_mean
0,10000032,29079034,39553978,2180-07-23 14:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,37.055556,37.055556,37.055556,NaN,NaN,NaN,NaN,NaN,NaN
1,10000032,29079034,39553978,2180-07-23 14:11:00,NaN,NaN,NaN,84.0,84.0,84.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10000032,29079034,39553978,2180-07-23 14:12:00,91.0,91.0,91.0,NaN,NaN,NaN,...,24.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,10000032,29079034,39553978,2180-07-23 14:13:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,98.0,98.0,98.0,NaN,NaN,NaN
4,10000032,29079034,39553978,2180-07-23 14:30:00,93.0,93.0,93.0,95.0,95.0,95.0,...,21.0,NaN,NaN,NaN,97.0,97.0,97.0,NaN,NaN,NaN

In [22]:
vars_of_interest_vitals = [
    "heartrate_mean",
    "sysbp_mean",
    "diasbp_mean",
    "resprate_mean",
    "glucose_mean",
]
nan_percentage_vitals = df_vitals.isna().mean() * 100
nan_percentage_vitals[vars_of_interest_vitals]

heartrate_mean    33.673056
sysbp_mean        36.345167
diasbp_mean       36.360021
resprate_mean     33.700441
glucose_mean      86.382835
dtype: float64

In [7]:
csv_path = Path("../../data/vents-vasopressor-sedatives-kdigo_stages_measured.csv")
df_vents = pd.read_csv(csv_path, sep=";")
df_vents.head()

    stay_id            charttime  vent  vasopressor  sedative
0  30000153  2174-09-29 10:16:00     0            0         0
1  30000153  2174-09-29 12:12:00     1            0         1
2  30000153  2174-09-29 12:27:00     1            0         1
3  30000153  2174-09-29 13:27:00     1            0         1
4  30000153  2174-09-29 14:00:00     1            0         0

In [8]:
vars_of_interest_vents = [
    "vasopressor",
    "sedative",
]
nan_percentage_vents = df_vents.isna().mean() * 100
nan_percentage_vents[vars_of_interest_vents]

vasopressor    0.0
sedative       0.0
dtype: float64

In [9]:
df_vents.columns.difference(['charttime','vent'])

Index(['sedative', 'stay_id', 'vasopressor'], dtype='object')